pip3 install timm

export TORCH_HOME=/youtu/fuxi-team2/persons/niceliu/models
export PYTHONPATH=/youtu/fuxi-team2-2/persons/jinxianglai/CLvision2022/mmdetection/code/avalanche:$PYTHONPATH

printf "1. Split train set and val set from ego_objects_challenge_train.json.\n" 
# or you can directly use the 2 annotation files generated by us, which are in the directory of 'annotations'.
python3 tools/dataSplit_submit.py

printf "2. Generate 5 annotation files for 5 incremental tasks from avalanche benchmark.\n"
python3 tools/CLtask_split.py 

printf "3. training...\n"
# Submited_Best
config=configs/clv-challenge/vfnet_r2_101_fpn_mdconv_1x_clv_json.py
bash tools/dist_train_json.sh $config 8

# CLV_1
#config=configs/clv-challenge/vfnet_r2_101_fpn_mdconv_1gpu_clv_json.py
#bash tools/dist_train_json.sh $config 1

# CLV_2
#config=configs/clv-challenge/vfnet_r2_101_fpn_mdconv_1gpu_clv_json_2.py
#bash tools/dist_train_json.sh $config 1

# CLV_3
#config=configs/clv-challenge/vfnet_r2_101_fpn_mdconv_1gpu_clv_json_3.py
#bash tools/dist_train_json.sh $config 1